# Generated by Django 5.2.2 on 2025-06-10 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_contributors', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('reward_message', models.TextField(blank=True)),
                ('milestone_messages', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wishlist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_goal', to='core.wishlistitem')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(max_length=254)),
                ('invited_phone', models.CharField(blank=True, max_length=15)),
                ('invited_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('ACCEPTED', 'پذیرفته شده'), ('DECLINED', 'رد شده'), ('EXPIRED', 'منقضی شده')], default='PENDING', max_length=20)),
                ('invitation_token', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.wishlistitem')),
            ],
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('TELEGRAM', 'تلگرام'), ('WHATSAPP', 'واتساپ'), ('INSTAGRAM', 'اینستاگرام'), ('TWITTER', 'توییتر'), ('SMS', 'پیامک'), ('EMAIL', 'ایمیل')], max_length=20)),
                ('share_content', models.TextField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to=settings.AUTH_USER_MODEL)),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='core.wishlistitem')),
            ],
            options={
                'unique_together': {('wishlist_item', 'shared_by', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='WishlistShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('PUBLIC', 'عمومی'), ('PRIVATE', 'خصوصی'), ('FRIENDS', 'دوستان'), ('LINK', 'با لینک')], default='PRIVATE', max_length=20)),
                ('share_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_contributions', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('show_progress', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_wishlists', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'shared_by')},
            },
        ),
    ]
