# Generated by Django 5.2.2 on 2025-06-10 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contributiongoal_wishlistinvitation_socialshare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('attempt_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لاگ تایید موبایل',
                'verbose_name_plural': 'لاگ\u200cهای تایید موبایل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('REGISTRATION', 'ثبت\u200cنام'), ('LOGIN', 'ورود'), ('PASSWORD_RESET', 'بازیابی رمز عبور'), ('PHONE_VERIFICATION', 'تایید شماره موبایل')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'تایید OTP',
                'verbose_name_plural': 'تایید\u200cهای OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'otp_type', 'is_verified'], name='core_otpver_phone_n_832f04_idx'), models.Index(fields=['expires_at'], name='core_otpver_expires_b4c0c3_idx')],
            },
        ),
    ]
