# Generated by Django 5.2.2 on 2025-06-10 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phoneverificationlog_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('challenge_type', models.CharField(choices=[('MATH', 'ریاضی ساده'), ('TEXT', 'تشخیص متن'), ('IMAGE', 'انتخاب تصویر'), ('RECAPTCHA', 'Google reCAPTCHA'), ('HCAPTCHA', 'hCaptcha')], max_length=20)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('user_answer', models.CharField(blank=True, max_length=100)),
                ('is_solved', models.BooleanField(default=False)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'چالش Captcha',
                'verbose_name_plural': 'چالش\u200cهای Captcha',
                'indexes': [models.Index(fields=['session_id', 'is_solved'], name='core_captch_session_d4ce37_idx'), models.Index(fields=['expires_at'], name='core_captch_expires_ac3bd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint_hash', models.CharField(max_length=64, unique=True)),
                ('user_agent', models.TextField()),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('browser_name', models.CharField(blank=True, max_length=50)),
                ('browser_version', models.CharField(blank=True, max_length=20)),
                ('plugins_hash', models.CharField(blank=True, max_length=64)),
                ('registration_attempts', models.PositiveIntegerField(default=0)),
                ('successful_registrations', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ردپای دستگاه',
                'verbose_name_plural': 'ردپای\u200cهای دستگاه',
                'indexes': [models.Index(fields=['fingerprint_hash'], name='core_device_fingerp_b28b56_idx'), models.Index(fields=['is_suspicious', 'risk_score'], name='core_device_is_susp_271f80_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPReputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('registration_attempts', models.PositiveIntegerField(default=0)),
                ('successful_registrations', models.PositiveIntegerField(default=0)),
                ('failed_otp_attempts', models.PositiveIntegerField(default=0)),
                ('captcha_failures', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=200)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امتیاز IP',
                'verbose_name_plural': 'امتیازات IP',
                'indexes': [models.Index(fields=['ip_address', 'is_blocked'], name='core_iprepu_ip_addr_91c301_idx'), models.Index(fields=['risk_score'], name='core_iprepu_risk_sc_609df1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('form_fill_time', models.FloatField(null=True)),
                ('typing_speed', models.FloatField(null=True)),
                ('mouse_movements', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('key_presses', models.PositiveIntegerField(default=0)),
                ('copy_paste_detected', models.BooleanField(default=False)),
                ('auto_fill_detected', models.BooleanField(default=False)),
                ('multiple_tabs', models.BooleanField(default=False)),
                ('time_on_page', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_human_like', models.BooleanField(default=True)),
                ('bot_probability', models.FloatField(default=0.0)),
                ('device_fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.devicefingerprint')),
            ],
            options={
                'verbose_name': 'تحلیل رفتار',
                'verbose_name_plural': 'تحلیل\u200cهای رفتار',
                'indexes': [models.Index(fields=['session_id'], name='core_behavi_session_02b37b_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_behavi_ip_addr_9395b1_idx')],
            },
        ),
    ]
