# Generated by Django 5.2.2 on 2025-06-10 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_captchachallenge_devicefingerprint_ipreputationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='ایمیل')),
                ('attempt_type', models.CharField(choices=[('SEND', 'ارسال'), ('VERIFY', 'تایید'), ('RESEND', 'ارسال مجدد')], max_length=10, verbose_name='نوع تلاش')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='موفق')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'لاگ تایید ایمیل',
                'verbose_name_plural': 'لاگ\u200cهای تایید ایمیل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='core_emailv_email_591807_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_emailv_ip_addr_69afe8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='ایمیل')),
                ('verification_type', models.CharField(choices=[('REGISTER', 'ثبت\u200cنام'), ('LOGIN', 'ورود'), ('RESET_PASSWORD', 'بازیابی رمز عبور'), ('CHANGE_EMAIL', 'تغییر ایمیل')], max_length=20, verbose_name='نوع تایید')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='توکن تایید')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='حداکثر تلاش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تایید ایمیل',
                'verbose_name_plural': 'تاییدهای ایمیل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'verification_type'], name='core_emailv_email_ec9248_idx'), models.Index(fields=['token'], name='core_emailv_token_606d0a_idx'), models.Index(fields=['created_at'], name='core_emailv_created_96d4e2_idx'), models.Index(fields=['expires_at'], name='core_emailv_expires_cd90f8_idx')],
            },
        ),
    ]
